"""Spiral Noether Theorem utilities.

This module encodes a concrete version of the Spiral Noether Theorem (SNT)
for the "Amundson" programme.  The symmetry of interest is a simultaneous
rotation and radial dilation generated by the spiral operator

.. math::
    \mathcal U(\theta, a) = e^{a\theta} R(\theta),

where :math:`R(\theta)` is the planar rotation matrix.  The associated
conserved quantity --- the *spiral momentum* --- is extracted from the field
configuration via the usual Noether current construction.  We also provide a
minimal decay model for the current inside an open quantum system governed by
GKSL dynamics.

The code favours explicit, numerically friendly formulas so that small thought
experiments can be run without symbolic tooling.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

import numpy as np


@dataclass
class SpiralNoetherResult:
    """Container for the Spiral Noether Theorem outputs.

    Attributes
    ----------
    conserved_current:
        The instantaneous spiral Noether current :math:`J^\mu_s` evaluated on
        the field.
    spiral_momentum_density:
        A scalar density proportional to the conserved charge.  This can be
        integrated over a hypersurface to obtain the total spiral momentum.
    gksl_decay_factor:
        Exponential damping factor predicted by the GKSL dissipator at the
        specified time horizon.
    """

    conserved_current: np.ndarray
    spiral_momentum_density: np.ndarray
    gksl_decay_factor: float


def spiral_operator(theta: float, a: float) -> np.ndarray:
    """Return the planar spiral operator matrix.

    Parameters
    ----------
    theta:
        Angular component of the motion.
    a:
        Logarithmic radial growth rate.

    Returns
    -------
    numpy.ndarray
        A :math:`2 \times 2` matrix representing the combined dilation and
        rotation.  Applying the matrix to a planar vector enacts the spiral
        symmetry transformation.
    """

    scale = np.exp(a * theta)
    cos_t, sin_t = np.cos(theta), np.sin(theta)
    return scale * np.array([[cos_t, -sin_t], [sin_t, cos_t]], dtype=float)


def spiral_generator(a: float) -> np.ndarray:
    """Return the Lie generator associated with the spiral symmetry."""

    return np.array([[a, -1.0], [1.0, a]], dtype=float)


def spiral_noether_current(field: np.ndarray, gradient: np.ndarray, a: float) -> np.ndarray:
    """Compute the spiral Noether current for a complex scalar field.

    The current is the familiar bilinear combination

    .. math::
        J^\mu_s = \Re[\bar\phi (\partial^\mu + a x^\mu) \phi],

    which is a direct transcription of the spiral generator action on the
    field configuration.

    Parameters
    ----------
    field:
        Complex amplitudes of the scalar field sampled on a grid.
    gradient:
        Matching gradient samples.  The final dimension must agree with the
        spatial dimensionality.
    a:
        Spiral dilation strength.
    """

    if field.ndim != gradient.ndim - 1:
        raise ValueError("Gradient tensor must have one extra trailing dimension")

    grad_term = np.real(np.conjugate(field)[..., None] * gradient)
    dilation_term = a * np.real(np.conjugate(field) * field)[..., None]
    return grad_term + dilation_term


def spiral_momentum_density(field: np.ndarray, a: float) -> np.ndarray:
    """Return the spiral momentum density :math:`\rho_s` for a field sample."""

    return 0.5 * (a * np.abs(field) ** 2)


def gksl_decay(current: np.ndarray, rates: Iterable[float], time: float) -> np.ndarray:
    """Apply GKSL exponential decay to a current profile.

    Parameters
    ----------
    current:
        Current samples to be damped.
    rates:
        Iterable of Lindblad rates :math:`\gamma_k`.
    time:
        Evolution time.
    """

    total_rate = float(np.sum(list(rates)))
    damping = np.exp(-total_rate * time)
    return current * damping


def evaluate_snt(field: np.ndarray, gradient: np.ndarray, a: float, rates: Iterable[float], time: float) -> SpiralNoetherResult:
    """Bundle the Spiral Noether analysis for convenient consumption."""

    current = spiral_noether_current(field, gradient, a)
    density = spiral_momentum_density(field, a)
    decay_factor = float(np.exp(-float(np.sum(list(rates))) * time))
    return SpiralNoetherResult(current, density, decay_factor)


__all__ = [
    "SpiralNoetherResult",
    "evaluate_snt",
    "gksl_decay",
    "spiral_generator",
    "spiral_momentum_density",
    "spiral_noether_current",
    "spiral_operator",
]
